"""Generate an ignored C++ configuration header from the project's .env file."""

from pathlib import Path

Import("env")  # type: ignore[name-defined]  # Provided by PlatformIO/SCons.


REQUIRED_KEYS = (
    "SPOTIFY_CLIENT_ID",
    "SPOTIFY_REFRESH_TOKEN",
    "WIFI_SETUP_NAME",
    "WIFI_SETUP_PASSWORD",
    "GLANCES_HOST",
    "GLANCES_PORT",
)


def read_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for line_number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[7:].lstrip()
        if "=" not in line:
            raise RuntimeError(f"Invalid environment entry at {path}:{line_number}")
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        values[key] = value
    return values


def cpp_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


project_dir = Path(env.subst("$PROJECT_DIR"))
private_env = project_dir / ".env"
example_env = project_dir / ".env.example"
source_env = private_env if private_env.exists() else example_env

if not source_env.exists():
    raise RuntimeError("Missing .env and .env.example; copy .env.example to .env first")

values = read_env(source_env)
missing = [key for key in REQUIRED_KEYS if not values.get(key)]
if missing:
    raise RuntimeError(f"Missing required values in {source_env}: {', '.join(missing)}")

try:
    glances_port = int(values["GLANCES_PORT"])
except ValueError as error:
    raise RuntimeError("GLANCES_PORT must be a number") from error
if not 1 <= glances_port <= 65535:
    raise RuntimeError("GLANCES_PORT must be between 1 and 65535")
if len(values["WIFI_SETUP_PASSWORD"]) < 8:
    raise RuntimeError("WIFI_SETUP_PASSWORD must contain at least 8 characters")

generated_header = project_dir / "include" / "generated_config.h"
generated_header.write_text(
    "// Generated by scripts/load_env.py. Do not edit or commit.\n"
    "#pragma once\n\n"
    f"constexpr char SPOTIFY_CLIENT_ID[] = {cpp_string(values['SPOTIFY_CLIENT_ID'])};\n"
    f"constexpr char SPOTIFY_REFRESH_TOKEN[] = {cpp_string(values['SPOTIFY_REFRESH_TOKEN'])};\n"
    f"constexpr char WIFI_SETUP_NAME[] = {cpp_string(values['WIFI_SETUP_NAME'])};\n"
    f"constexpr char WIFI_SETUP_PASSWORD[] = {cpp_string(values['WIFI_SETUP_PASSWORD'])};\n"
    f"constexpr char GLANCES_HOST[] = {cpp_string(values['GLANCES_HOST'])};\n"
    f"constexpr unsigned int GLANCES_PORT = {glances_port};\n",
    encoding="utf-8",
)

if source_env == example_env:
    print("Warning: .env not found; building with placeholder values from .env.example")
